---
title: "Graphics with ggplot2"
author: "Dave"
date: "10/22/2018"
output: html_document
---

# Learning ggplot2

We're learning ggplot2 It's going to be amazing.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Data

```{r loading data}
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

## working w/ data

```{r viewing data}
head(ca)
View(ca)
```
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors
                 ))




```

```{r}
head(ca)

```

```{r}
ggplot(data = ca)

```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() +
  theme(legend.title=element_blank())
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color =state)) +
  labs(x = "Year",
       y = "Visitation",
       title = "Southeast States National Park Visitation") +
  theme_light() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust =1, size =14))
```
```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors)) +
  facet_wrap(~state)
```
```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free")
```
```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors, color = park_name),
              width = 0.1,
              alpha = 0.4) +
  coord_flip() +
  theme(legend.position = "none")
```
```{r}
ggplot(se,) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()
```
```{r}
ggplot(data = acadia) +
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors)) +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()
```
```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth(color = "red") +
  labs(title = "Acadia National Park Visualization",
       y = "Visualization",
       x = "Year") +
  theme_bw
```
```{r}
ggplot(data = visit_16, aes(x = state)) +
  geom_bar()
```
```{r}
visit acadia
```
```{r}
ggplot(data = visit_16,aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity")
```
```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")
```

```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.png"", myplot, height = 5, width = 5, units = "in")
```

